AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  ApiGatewayApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: uat
        EndpointConfiguration: REGIONAL

  RestApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties: 
      ApiId: !Ref ApiGatewayApi
      ApiMappingKey: national-museum-prints
      DomainName: uat.heniapi.com
      Stage: !Ref ApiGatewayApi.Stage
      
  NationalMuseumPrintGQL:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NationalMuseumPrintGQL-uat
      Handler: dist/lambda/index.handler
      Layers:
        - 'arn:aws:lambda:eu-west-2:275989709466:layer:axiox-graphql-bundle:1'
      Environment:
        Variables:
          NODE_ENV: uat
          API_URL: 'https://api.harvardartmuseums.org/object'
          API_KEY: 'c28e4be0-4c0e-11ea-90d6-25d9a9fe80fc'
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 500
      Description: A GraphQL Lambda function for retreiving National Museum Prints.
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: ANY
            RestApiId: !Ref ApiGatewayApi