- pipeline: "Dev"
  on: "EVENT"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/dev"
  priority: "NORMAL"
  fetch_all_refs: true
  fail_on_prepare_env_warning: true
  actions:
  - action: "TS compile"
    type: "BUILD"
    working_directory: "/buddy/national-museum-print-api"
    docker_image_name: "library/node"
    docker_image_tag: "14"
    setup_commands:
    - "npm install -g rimraf"
    - "npm install -g typescript"
    - "npm install apollo-server-lambda"
    - "npm install graphql"
    - "npm install axios"
    execute_commands:
    - "npm run build"
    volume_mappings:
    - "/:/buddy/national-museum-print-api"
    cache_base_image: true
    shell: "BASH"

  - action: "SAM VALIDATE"
    type: "AWS_CLI"
    region: "eu-west-2"
    execute_commands:
    - "sam validate -t ./sam.dev.yml --config-env dev"
    setup_commands:
    - "/aws/env/bin/pip install aws-sam-cli"
    shell: "SH"
    integration_hash: "Pr1gO3GWpmbkBPR6azJn4KRjLM"

  - action: "SAM BUILD"
    type: "AWS_CLI"
    region: "eu-west-2"
    execute_commands:
    - "sam build -t ./sam.dev.yml --config-env dev"
    setup_commands:
    - "/aws/env/bin/pip install aws-sam-cli"
    - "apt update"
    - "apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates"
    - "curl -sL https://deb.nodesource.com/setup_14.x | bash -"
    - "apt -y install nodejs"
    shell: "SH"
    integration_hash: "Pr1gO3GWpmbkBPR6azJn4KRjLM"

  # - action: "RUN TESTS"
  #   type: "BUILD"
  #   working_directory: "/buddy/national-museum-print-api"
  #   docker_image_name: "library/node"
  #   docker_image_tag: "12"
  #   execute_commands:
  #   - "npm install"
  #   - "npm run integ-test-dev"
  #   volume_mappings:
  #   - "/:/buddy/national-museum-print-api"
  #   shell: "BASH"
  
  - action: "SAM DEPLOY"
    type: "AWS_CLI"
    region: "eu-west-2"
    execute_commands:
    - "sam deploy -t ./sam.dev.yml --config-env dev"
    setup_commands:
    - "/aws/env/bin/pip install aws-sam-cli"
    shell: "SH"
    integration_hash: "Pr1gO3GWpmbkBPR6azJn4KRjLM"